      PROGRAM SOX2C1EDRV    
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)

      COMMON//ICORE(1) 
      COMMON/ISTART/I0
      COMMON/MACHSP/IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON/IOPOS/ICRSIZ,ICHSZ,IOFF(2),LENREC
C
      call initenv('MODULE')
      call walltime(0)
C
C INITIALIZE PROGRAM IN THE CFOUR ENVIRONEMENT
C 
C  a) CALL FIRST MCHPRM TO INITIALIZE /MVDINT/
C  a) CALL THEN CRAPSI WITH IENTRY=100
C
      CALL MCHPRM
      IENTRY=0
      CALL CRAPSI(ICORE,IUHF,IENTRY)
C
C SET MAXCOR IN FLOATING POINT WORDS
C
      MAXCOR=ICRSIZ/IINTFP
C
      CALL READIN(.FALSE.,ICORE(I0),MAXCOR)
C
      ISTART=I0
      CALL EVALAO(ICORE(ISTART),MAXCOR)
C
      CALL CRAPSO
      call walltime(1)

      STOP 
      END
